### PR TITLE
chore: add retention rate query

### PR DESCRIPTION
**Pull request by zovt**
Example output:

These columns match what was requested in the ticket, though maybe we can drop the `start` column and just have `new` and `end`? 🤔

### CODE REVIEW

**Comment by digitalcora** [comment]
Certainly it seems like only two of the three columns should be required, as the third can then be derived — I'd go with whatever is easiest in the SQL. We should probably also make the value `0` instead of `null` where applicable, otherwise we'd have to manually correct those values if loaded into a spreadsheet or other program.

Just looking at that screenshot, it seems like there's an issue with the dates... after February, the end of each period is the 28th of the month, but the following months have more than 28 days.

**Comment by zovt** [comment]
> Just looking at that screenshot, it seems like there's an issue with the dates... after February, the end of each period is the 28th of the month, but the following months have more than 28 days.

Yeah... I think it's probably related to how Postgres handles monthly intervals. I'll fiddle with it and see if I can peg it to the end of each month easily

**Comment by digitalcora** [comment]
This looks good, though I think we should be a bit clearer about the meaning of the columns, since there is some complexity hidden in there. Maybe `new_active_users` and `total_active_users`? (we already use the term "active" in other reports to describe users who have at least one unpaused subscription)

Also, "retention rate" seems like... maybe not the right name for what this report is, vs. the original intent? I'm not sure what a better name would be. Maybe "Monthly new active users"?

**Review by digitalcora — APPROVED** [review]
📆 👥 ✅

**Pull request merged**
