### PR TITLE
feat: switch to OIDC library that's actually released

### PR DESCRIPTION
**Pull request by paulswartz**
- Oidcc: https://hexdocs.pm/oidcc/readme.html
- UeberauthOidcc: https://hexdocs.pm/ueberauth_oidcc/readme.html

As far as I can tell, the test failures are only in `alerts_processor` and are also happening on `main`.

### CODE REVIEW

**Comment by arkadyan** [comment]
That failing test smells like a GTFS change issue unrelated to this PR. I can check that out.

**Comment by arkadyan** [comment]
https://github.com/mbta/alerts_concierge/pull/1372 should fix that test case.

**Review by arkadyan — APPROVED** [review]
Thanks, this is great. It took me a minute to spot the extra "c" and understand what I was looking at—I hadn't come across this library before. This is very timely as I'm just today adding SSO support to our new project, so I will shift direction and use this library.

**Comment by paulswartz** [comment]
It's a fairly new library, but I wanted something that 1) supported log out fairly natively 2) was in Hex and ended up with Oidcc (even OpenID certified!) and the UeberauthOidcc wrapper around it.

**Comment by arkadyan** [comment]
Ugh, the data changed again. I have a new fix.

**Pull request merged**
